"""add title column to Event

Revision ID: e17d1355f536
Revises: 37d354226d58
Create Date: 2025-08-18 17:58:59.508584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17d1355f536'
down_revision: Union[str, Sequence[str], None] = '37d354226d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(), nullable=False, server_default=sa.text("''")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
